### ISSUE TITLE
Update to 1.5?

### ISSUE THREAD

**Issue by kramat** [TrueOsiris/docker-ptmagic#1]
Great work! Is it also possible to update to version 1.5.2 (latest version)?

**Comment by TrueOsiris** [comment]
There's an issue it seems, but working on it.
Just back from holliday.
The main issue is that there's an error in the dotnet package dependencies on ubuntu 17.10

**Comment by TrueOsiris** [comment]
Ok updated to v1.5.2.
Tested succesfully on my own environment.
I've created a separate image on ubuntu + dotnet, so this won't cause dependency issues in the future.
